version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - check
      - cs-resolve
      - docs
      - download-problems
      - download-verify-artifact
      - merge-result
      - merge-verify-files
      - oj-resolve
      - parse-doxygen
      - setup
      - testing
      - upload-verify-artifact
      - verify
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
